
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('C001','Clip','Clips Double 1"',50,30,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('C002','Clip','Clips Double 2"',50,30,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('C003','Clip','Clips Double 3/4"',50,30,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('C004','Clip','Clips Paper Large',50,30,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('C005','Clip','Clips Paper Medium',50,30,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('C006','Clip','Clips Paper Small',50,30,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E001','Envelope','Envelope Brown (3"x6")',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E002','Envelope','Envelope Brown (3"x6") w/ Window',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E003','Envelope','Envelope Brown (5"x7")',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E004','Envelope','Envelope Brown (5"x7") w/ Window',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E005','Envelope','Envelope White (3"x6")',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E006','Envelope','Envelope White (3"x6") w/ Window',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E007','Envelope','Envelope White (5"x7")',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E008','Envelope','Envelope White (5"x7") w/ Window',600,400,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E020','Eraser','Eraser (hard)',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E021','Eraser','Eraser (soft)',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E030','Exercise','Exercise Book (100 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E031','Exercise','Exercise Book (120 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E032','Exercise','Exercise Book A4 Hardcover (100 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E033','Exercise','Exercise Book A4 Hardcover (120 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E034','Exercise','Exercise Book A4 Hardcover (200 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E035','Exercise','Exercise Book Hardcover (100 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('E036','Exercise','Exercise Book Hardcover (120 pg)',100,50,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F020','File','File Separator',100,50,'Set');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F021','File','File-Blue Plain',200,100,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F022','File','File-Blue with Logo',200,100,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F023','File','File-Brown w/o Logo',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F024','File','File-Brown with Logo',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F031','File','Folder Plastic Blue',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F032','File','Folder Plastic Clear',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F033','File','Folder Plastic Green',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F034','File','Folder Plastic Pink',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('F035','File','Folder Plastic Yellow',200,150,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H011','Pen','Highlighter Blue',100,80,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H012','Pen','Highlighter Green',100,80,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H013','Pen','Highlighter Pink',100,80,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H014','Pen','Highlighter Yellow',100,80,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H031','Puncher','Hole Puncher 2 holes',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H032','Puncher','Hole Puncher 3 holes',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('H033','Puncher','Hole Puncher Adjustable',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P010','Pad','Pad Postit Memo 1"x2"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P011','Pad','Pad Postit Memo 1/2"x1"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P012','Pad','Pad Postit Memo 1/2"x2"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P013','Pad','Pad Postit Memo 2"x3"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P014','Pad','Pad Postit Memo 2"x4"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P015','Pad','Pad Postit Memo 2"x4"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P016','Pad','Pad Postit Memo 3/4"x2"',100,60,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P020','Paper','Paper Photostat A3',500,500,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P021','Paper','Paper Photostat A4',500,500,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P030','Pen','Pen Ballpoint Black',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P031','Pen','Pen Ballpoint Blue',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P032','Pen','Pen Ballpoint Red',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P033','Pen','Pen Felt Tip Black',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P034','Pen','Pen Felt Tip Blue',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P035','Pen','Pen Felt Tip Red',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P036','Pen','Pen Transparency Permanent',100,50,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P037','Pen','Pen Transparency Soluble',100,50,'Packet');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P038','Pen','Pen Whiteboard Marker Black',100,50,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P039','Pen','Pen Whiteboard Marker Blue',100,50,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P040','Pen','Pen Whiteboard Marker Green',100,50,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P041','Pen','Pen Whiteboard Marker Red',100,50,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P042','Pen','Pencil 2B',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P043','Pen','Pencil 2B with Eraser End',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P044','Pen','Pencil 4H',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P045','Pen','Pencil B',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('P046','Pen','Pencil B with Eraser End',100,50,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('R001','Ruler','Ruler 6"',50,20,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('R002','Ruler','Ruler 12"',50,20,'Dozen');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S100','Scissors','Scissors',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S040','Tape','Scotch Tape',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S041','Tape','Scotch Tape Dispenser',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S101','Sharpener','Sharpener',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S010','Shorthand','Shorthand Book (100 pg)',100,80,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S011','Shorthand','Shorthand Book (120 pg)',100,80,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S012','Shorthand','Shorthand Book (80 pg)',100,80,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S020','Stapler','Stapler No. 28',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S021','Stapler','Stapler No. 36',50,20,'Each');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S022','Stapler','Stapler No. 28',50,20,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('S023','Stapler','Stapler No. 36',50,20,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T001','Tacks','Thumb Tacks Large',10,10,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T002','Tacks','Thumb Tacks Medium',10,10,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T003','Tacks','Thumb Tacks Small',10,10,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T020','Tparency','Transparency Blue',100,200,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T021','Tparency','Transparency Clear',500,400,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T022','Tparency','Transparency Green',100,200,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T023','Tparency','Transparency Red',100,200,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T024','Tparency','Transparency Reverse Blue',100,200,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T025','Tparency','Transparency Cover 3M',500,400,'Box');
INSERT INTO Catalogues(Item_Num,Category,Description,Reorder_Level,Reorder_Quantity,UOM) VALUES ('T100','Tray','Trays In/Out',20,10,'Set');
